name: Publish Package

on:
  release:
    types: [published]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full git history for hatch-vcs
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Build and publish the Python package
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv build
        uv publish
